apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "ft_services"
spec:
  type: LoadBalancer 
  ports:
  - port: 21
    targetPort: 21
    name: ftps
  - port: 20
    targetPort: 20
    name: ftps-data
  - port: 21022
    targetPort: 21022
    name: ftps-p22
  - port: 21021
    targetPort: 21021
    name: ftps-p21
  - port: 21020
    targetPort: 21020
    name: ftps-p20
  selector:
    app: ftps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      volumes:
        - name: ftps-persistent-storage
          persistentVolumeClaim:
            claimName: ftps-pv-claim
      containers:
      - name: ftps
        image: my-ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 20
          name: ftps-data
        - containerPort: 21022
          name: ftps-p22
        - containerPort: 21021
          name: ftps-p21
        - containerPort: 21020
          name: ftps-p20
        volumeMounts:
        - name: ftps-persistent-storage
          mountPath: /ftps_data