CREATE USER 'user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%' WITH GRANT OPTION;
CREATE DATABASE wordpress;
GRANT ALL PRIVILEGES ON wordpress.* TO 'user'@'%' IDENTIFIED BY '123';
DROP DATABASE test;
FLUSH PRIVILEGES;